CONFIG_NAME: mainnet
PRESET_BASE: mainnet
TERMINAL_TOTAL_DIFFICULTY: '58750000000000000000000'
TERMINAL_BLOCK_HASH: '0x0000000000000000000000000000000000000000000000000000000000000000'
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: '18446744073709551615'
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: '16384'
MIN_GENESIS_TIME: '1606824000'
GENESIS_FORK_VERSION: '0x00000000'
GENESIS_DELAY: '604800'
ALTAIR_FORK_VERSION: '0x01000000'
ALTAIR_FORK_EPOCH: '0'
BELLATRIX_FORK_VERSION: '0x02000000'
BELLATRIX_FORK_EPOCH: '0'
CAPELLA_FORK_VERSION: '0x03000000'
CAPELLA_FORK_EPOCH: '0'
DENEB_FORK_VERSION: '0x04000000'
DENEB_FORK_EPOCH: '0'
ELECTRA_FORK_VERSION: '0x05000000'
ELECTRA_FORK_EPOCH: '0'
FULU_FORK_VERSION: '0x06000000'
FULU_FORK_EPOCH: '411392'
GLOAS_FORK_VERSION: '0x07000000'
GLOAS_FORK_EPOCH: '18446744073709551615'
SECONDS_PER_SLOT: '12'
SECONDS_PER_ETH1_BLOCK: '14'
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: '256'
SHARD_COMMITTEE_PERIOD: '256'
ETH1_FOLLOW_DISTANCE: '2048'
SUBNETS_PER_NODE: '2'
INACTIVITY_SCORE_BIAS: '4'
INACTIVITY_SCORE_RECOVERY_RATE: '16'
EJECTION_BALANCE: '16000000000'
MIN_PER_EPOCH_CHURN_LIMIT: '4'
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: '8'
CHURN_LIMIT_QUOTIENT: '65536'
PROPOSER_SCORE_BOOST: '40'
DEPOSIT_CHAIN_ID: '1'
DEPOSIT_NETWORK_ID: '1'
DEPOSIT_CONTRACT_ADDRESS: '0x00000000219ab540356cbb839cbe05303d7705fa'
GAS_LIMIT_ADJUSTMENT_FACTOR: '1024'
MAX_PAYLOAD_SIZE: '10485760'
MAX_REQUEST_BLOCKS: '1024'
MIN_EPOCHS_FOR_BLOCK_REQUESTS: '33024'
TTFB_TIMEOUT: '5'
RESP_TIMEOUT: '10'
ATTESTATION_PROPAGATION_SLOT_RANGE: '32'
MAXIMUM_GOSSIP_CLOCK_DISPARITY: '500'
MESSAGE_DOMAIN_INVALID_SNAPPY: '0x00000000'
MESSAGE_DOMAIN_VALID_SNAPPY: '0x01000000'
ATTESTATION_SUBNET_PREFIX_BITS: '6'
MAX_REQUEST_BLOCKS_DENEB: '128'
MAX_REQUEST_BLOB_SIDECARS: '768'
MAX_REQUEST_DATA_COLUMN_SIDECARS: '16384'
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: '4096'
BLOB_SIDECAR_SUBNET_COUNT: '6'
MAX_BLOBS_PER_BLOCK: '6'
MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA: '128000000000'
MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT: '256000000000'
MAX_BLOBS_PER_BLOCK_ELECTRA: '9'
BLOB_SIDECAR_SUBNET_COUNT_ELECTRA: '9'
MAX_REQUEST_BLOB_SIDECARS_ELECTRA: '1152'
NUMBER_OF_CUSTODY_GROUPS: '128'
DATA_COLUMN_SIDECAR_SUBNET_COUNT: '128'
SAMPLES_PER_SLOT: '8'
CUSTODY_REQUIREMENT: '4'
BLOB_SCHEDULE:
- EPOCH: '412672'
  MAX_BLOBS_PER_BLOCK: '15'
- EPOCH: '419072'
  MAX_BLOBS_PER_BLOCK: '21'
VALIDATOR_CUSTODY_REQUIREMENT: '8'
BALANCE_PER_ADDITIONAL_CUSTODY_GROUP: '32000000000'
MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS: '4096'
