[package]
name = "validator_store"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
eth2 = { workspace = true }
slashing_protection = { workspace = true }
types = { workspace = true }
